---
title: "Size"
output: html_document
---

```{r Packages}
library(tidyverse)
library(dplyr)
library(glmmTMB)
library(DHARMa)
library(emmeans)
```

```{r Load Data}
Platy_na_xc <- read.csv("area.csv")
Mean_Areas <- read.csv("m_area.csv")  
```

```{r Model}
Platy_na_xc$Day=factor(Platy_na_xc$Day)                         #Re-assign factors

model = glmmTMB(polyp_area ~ Treatment*poly(nDay,3) + (1|Tank/Recruit_ID) +  #Model with day as a polynomial
                   ar1(0 + Day|Recruit_ID),
                 #family = Gamma(link = 'log'),
                  family = gaussian(link = 'log'),
            data=Platy_na_xc,
            REML = TRUE)

summary(model)

simulateResiduals(model, plot = TRUE)
```

```{r Pairwise Contrasts}
size_model_conts<- emmeans::emmeans(model, ~ Treatment|nDay, at=list(nDay = c(67)), type = 'response') %>%
  pairs() %>%
  summary(infer = TRUE) %>%
  as.data.frame() %>% 
  group_by(nDay) %>%
  #arrange(ratio) %>%
  mutate(contrast = factor(contrast, levels = unique(contrast))) %>%
  mutate(Flag = factor(ifelse(lower.CL > 1, 1, ifelse(upper.CL < 1, -1, 0)))) %>%
  ggplot(aes(x = ratio, y = contrast, colour = Flag)) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_pointrange(aes(xmin = lower.CL, xmax = upper.CL)) +
  scale_x_continuous(trans = scales::log2_trans()) +
  scale_colour_manual(breaks = c(-1,0,1), values = c("red", "black", "green")) +
  facet_grid(~nDay)+
  theme(plot.title = element_text(size = 20, face="bold",hjust=0.5),
        axis.title.x = element_text(size = 18, face="bold"),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 8, face="bold"),
        axis.text.y = element_text(size = 14, face="bold"),
        legend.title = element_text(size = 16, face="bold"),
        legend.text = element_text(size = 12, face="bold"))+
  labs(title = "Contrasts")
size_model_conts
```

```{r Individual Contrasts}
Platy_na_xc$Treatment %>% levels()

cMat <- cbind("Single vs Mix" = c(1/3, -1/4, -1/4, -1/4, -1/4, 1/3, 1/3))

cMata <- cbind("C Alone vs C Mix" = c(1/1, -1/4, -1/4, -1/4, -1/4, 0, 0))

cMatb <- cbind("Dwt vs Dhe" = c(0, 1/3, -1/3, -1/3, 1/3, -1/3, 1/3))  

cMatc <- cbind("match vs mismatch" = c(0, -1/2, -1/2, 1/2, 1/2, 0, 0))  

cMatx <- cbind("Single vs Mix" = c(0, -1/4, -1/4, -1/4, -1/4, 1/2, 1/2))

crossprod(cMat)
emmeans::emmeans(model, ~ Treatment|nDay, at=list(nDay = 67), type = 'response') %>%
  contrast(method = list(Treatment = cMat))
crossprod(cMatx)
emmeans::emmeans(model, ~ Treatment|nDay, at=list(nDay = 67), type = 'response') %>%
  contrast(method = list(Treatment = cMatx))
crossprod(cMata)
emmeans::emmeans(model, ~ Treatment|nDay, at=list(nDay = 67), type = 'response') %>%
  contrast(method = list(Treatment = cMata))
crossprod(cMatb)
emmeans::emmeans(model, ~ Treatment|nDay, at=list(nDay = 67), type = 'response') %>%
  contrast(method = list(Treatment = cMatb))
crossprod(cMatc)
emmeans::emmeans(model, ~ Treatment|nDay, at=list(nDay = 67), type = 'response') %>%
  contrast(method = list(Treatment = cMatc))
```

```{r Graph}
 Mean_Areas %>%
    ggplot(aes(x = Day, y = area, group = Treatment)) +
    geom_line(aes(color=Treatment), size=1)+
  geom_ribbon(aes(ymin=Mean_Areas$lse, ymax=Mean_Areas$use, fill = factor(Treatment)),color = NA, alpha = 0.18 )+
    scale_color_manual(values = c("#f678d8", "#1f59c5", "#82ad0f", "#ee8e36", "#16b4eb", "#15b418", "#bc58dc")) +
  scale_fill_manual(values = c("#f678d8", "#1f59c5", "#82ad0f", "#ee8e36", "#16b4eb", "#15b418", "#bc58dc"))+
  theme_bw()+
    scale_x_continuous(breaks = seq(0, 70, by = 10))
```

