---
title: "Survival"
output: html_document
---

```{r Packages}
library(tidyverse)
library(dplyr)
library(plotrix)
library(glmmTMB)
library(DHARMa)
library(emmeans)
```

```{r Load Data}
surv_counts_agg_xcx <- read.csv("surv.csv")  
```

```{r Survival Model}
model_agg_xc = glmmTMB(cbind(count_alive, count - count_alive) ~  Treatment*Day + (1|Tank), 
                    data = surv_counts_agg_xcx, 
                    family = binomial(link = "cloglog"), 
                    REML = TRUE)                

summary(model_agg_xc)

simulateResiduals(model_agg_xc, plot = TRUE)
```

```{r Paired contrasts}
surv_model_conts<- emmeans::emmeans(model_agg_xc, ~ Treatment|Day, at=list(Day = c(70)), type = 'response') %>%
  pairs() %>%
  summary(infer = TRUE) %>%
  as.data.frame() %>% 
  mutate(Flag = factor(ifelse(asymp.LCL > 0, 1, ifelse(asymp.UCL < 0, -1, 0)))) %>%
  ggplot(aes(x = estimate, y = contrast, colour = Flag)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_pointrange(aes(xmin = asymp.LCL, xmax = asymp.UCL)) +
  #scale_x_continuous(trans = scales::log2_trans()) +
  scale_colour_manual(breaks = c(-1,0,1), values = c("red", "black", "green")) +
  facet_grid(~Day)+
  theme(plot.title = element_text(size = 20, face="bold",hjust=0.5),
        axis.title.x = element_text(size = 18, face="bold"),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 8, face="bold"),
        axis.text.y = element_text(size = 14, face="bold"),
        legend.title = element_text(size = 16, face="bold"),
        legend.text = element_text(size = 12, face="bold"))+
  labs(title = "Contrasts")
surv_model_conts
```

```{r Individual contrasts}
surv_counts_agg_xcx$Treatment %>% levels()

cMat <- cbind("Single vs Mix" = c(1/4, 1/4, 1/4, 1/4, -1/3, -1/3, -1/3)) #sig

cMata <- cbind("Dwt vs Dhe" = c(1/3, -1/3, -1/3, 1/3, 0, 1/3, -1/3))  #NS

cMatb <- cbind("single vs Mix wo bad" = c(0, 1/3, 1/3, 1/3, -1/3, -1/3, -1/3)) #no difference when bad one is excluded

cMatc <- cbind("match vs mismatch" = c(-1/2, -1/2, 1/2, 1/2, 0, 0, 0))  #Sig


crossprod(cMat)
emmeans::emmeans(model_agg_xc, ~ ~ Treatment|Day, at=list(Day = 70), type = 'response') %>%
  contrast(method = list(Treatment = cMat))
crossprod(cMata)
emmeans::emmeans(model_agg_xc, ~ ~ Treatment|Day, at=list(Day = 70), type = 'response') %>%
  contrast(method = list(Treatment = cMata))
crossprod(cMatb)
emmeans::emmeans(model_agg_xc, ~ ~ Treatment|Day, at=list(Day = 70), type = 'response') %>%
  contrast(method = list(Treatment = cMatb))
crossprod(cMatc)
emmeans::emmeans(model_agg_xc, ~ ~ Treatment|Day, at=list(Day = 70), type = 'response') %>%
  contrast(method = list(Treatment = cMatc))
```

```{r Graph}
P1_sumq <- surv_counts_agg_xcx %>%
  group_by(Treatment,Day) %>%
  summarise(
    count = n(),
    mean = mean(survival, na.rm = TRUE),
    se = std.error(survival, na.rm = TRUE))

P1_sumsq <- P1_sumq %>%
  mutate(use = se+mean)

P1_sumulq <- P1_sumsq %>%
  mutate(lse = mean-se)

P1_sumulq %>%
  ggplot(aes(x = Day, y = mean, color = Treatment)) +
  geom_line(size=1)+
  geom_ribbon(aes(ymin=P1_sumulq$lse, ymax=P1_sumulq$use, fill = factor(Treatment)),color = NA, alpha = 0.18 )+
 scale_color_manual(values = c("#f678d8", "#15b418", "#bc58dc", "#ee8e36","#1f59c5", "#82ad0f", "#16b4eb")) +
  scale_fill_manual(values = c("#f678d8", "#15b418", "#bc58dc", "#ee8e36","#1f59c5", "#82ad0f", "#16b4eb"))+
  theme_bw()+
  xlim(11,70)
```